name: flutter_clobber
description: "Clobber new 🦄"

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
